# Generated by Django 2.2.9 on 2022-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Напишите ваше мнение', verbose_name='Текст комментария'),
        ),
    ]
